# Codex
# never
# on-request

approval_policy = "never"
sandbox_mode = "workspace-write"

[windows]
sandbox = "unelevated"

[sandbox_workspace_write]
  writable_roots = [
    'D:\GitRepo\SUMMONER_Refactor\Workpiece\Summoner', # Summoner 작업 공간
    'D:\GitRepo\SUMMONER_Refactor\Workpiece\Summoner\.codex', # Codex 작업 공간
    'D:\GitRepo\SUMMONER_Refactor\Workpiece\Summoner\.agents', # Agent 작업 공간
    'D:\GitRepo\SUMMONER_Refactor\.git', # 깃

    'D:\UnityProjects\SUMMONER_Repo\Workpiece\Summoner',
    'D:\UnityProjects\SUMMONER_Repo\Workpiece\Summoner\.codex',
    'D:\UnityProjects\SUMMONER_Repo\Workpiece\Summoner\.agents',
    'D:\UnityProjects\SUMMONER_Repo\.git'
  ]

# Unity MCP

[mcp_servers.mcp-unity]
command = "node"
args = ["LocalPackages/com.gamelovers.mcp-unity/Server~/build/index.js"]

[mcp_servers.mcp-unity.tools.recompile_scripts]
approval_mode = "auto"

[mcp_servers.mcp-unity.tools.run_tests]
approval_mode = "auto"

[mcp_servers.mcp-unity.tools.list_assets]
approval_mode = "auto"

[mcp_servers.mcp-unity.tools.find_assets]
approval_mode = "auto"

[mcp_servers.mcp-unity.tools.get_scene_info]
approval_mode = "auto"
